<?php
return [
    "DROP TABLE TST_5DTA.K_USERPRF",
"CREATE TABLE TST_5DTA.K_USERPRF ( 
--  SQL150B   10   REUSEDLT(*NO) in table K_USERPRF in TST_5DTA ignored. 
	US_USER CHAR(10) CCSID 37 NOT NULL DEFAULT '' , 
	US_COMP CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	US_LOCN CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	US_BUYR CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	US_BIRTH DATE NOT NULL DEFAULT CURRENT_DATE , 
	US_LASTUPD DATE NOT NULL DEFAULT CURRENT_DATE , 
	US_DATFMT CHAR(4) CCSID 37 NOT NULL DEFAULT '' , 
	US_TIMFMT CHAR(4) CCSID 37 NOT NULL DEFAULT '' , 
	US_TIMADJS DECIMAL(3, 0) NOT NULL DEFAULT 0 , 
	US_ALARM DECIMAL(1, 0) NOT NULL DEFAULT 0 , 
	US_DEALAL CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	US_DEALPI CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	US_DATESIX DECIMAL(1, 0) NOT NULL DEFAULT 0 , 
	US_EWINDOW DECIMAL(1, 0) NOT NULL DEFAULT 0 , 
	US_ORDVIEW DECIMAL(1, 0) NOT NULL DEFAULT 0 , 
	US_ORDMODE CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	US_PRDVIEW DECIMAL(1, 0) NOT NULL DEFAULT 0 , 
	US_PRDOPTN DECIMAL(1, 0) NOT NULL DEFAULT 0 , 
	US_HISDSPL DECIMAL(1, 0) NOT NULL DEFAULT 0 , 
	US_TRACKSG DECIMAL(3, 3) NOT NULL DEFAULT 0 , 
	US_UNITDSP DECIMAL(1, 0) NOT NULL DEFAULT 0 , 
	US_SELCHEK CHAR(2) CCSID 37 NOT NULL DEFAULT '' , 
	US_PRODSUM DECIMAL(1, 0) NOT NULL DEFAULT 0 , 
	US_MULTWRN DECIMAL(1, 0) NOT NULL DEFAULT 0 , 
	US_ALTVIEW DECIMAL(1, 0) NOT NULL DEFAULT 0 , 
	US_LOGWARN DECIMAL(3, 0) NOT NULL DEFAULT 0 , 
	US_EXPNOTE DECIMAL(3, 0) NOT NULL DEFAULT 0 , 
	US_F3_WARN DECIMAL(1, 0) NOT NULL DEFAULT 0 , 
	US_CUR1010 DECIMAL(1, 0) NOT NULL DEFAULT 0 , 
	US_CSTWARN DECIMAL(1, 0) NOT NULL DEFAULT 0 , 
	US_ARVDATE DECIMAL(1, 0) NOT NULL DEFAULT 0 , 
	US_AUTORND DECIMAL(1, 0) NOT NULL DEFAULT 0 , 
	US_AUTOFRZ DECIMAL(1, 0) NOT NULL DEFAULT 0 , 
	US_DFTLFRZ DATE NOT NULL DEFAULT CURRENT_DATE , 
	US_SELVIEW DECIMAL(1, 0) NOT NULL DEFAULT 0 )   
	  
	RCDFMT RK_USERPRF ",
  
"LABEL ON TABLE TST_5DTA.K_USERPRF 
	IS 'User preferences                                US' ",
  
"LABEL ON COLUMN TST_5DTA.K_USERPRF 
( US_USER IS 'User                ID' , 
	US_COMP IS 'Company             ID                  default' , 
	US_LOCN IS 'Location            ID                  default' , 
	US_BUYR IS 'Buy                 group               default' , 
	US_BIRTH IS 'User                birth               date' , 
	US_LASTUPD IS 'User                last                update' , 
	US_DATFMT IS 'Date                format              default' , 
	US_TIMFMT IS 'Time                format              default' , 
	US_TIMADJS IS 'Time                adjustment          hours' , 
	US_ALARM IS 'Alarm               preference          flag' , 
	US_DEALAL IS 'Deal                allowances          $,D,%' , 
	US_DEALPI IS 'Deal                price incre         $,D,%' , 
	US_DATESIX IS 'Date entry          6 digit             flg' , 
	US_EWINDOW IS 'If error            display window' , 
	US_ORDVIEW IS 'Order               summary             view' , 
	US_ORDMODE IS 'Order               summary             mode' , 
	US_PRDVIEW IS 'Product             summary             view' , 
	US_PRDOPTN IS 'Product             summary             option' , 
	US_HISDSPL IS 'Product             history             type' , 
	US_TRACKSG IS 'Product             display             T/S >' , 
	US_UNITDSP IS 'Unit                order display       1-6' , 
	US_SELCHEK IS 'Select              check               default' , 
	US_PRODSUM IS 'Prod sum            reverse             image' , 
	US_MULTWRN IS 'SOQ                 multiple            warning' , 
	US_ALTVIEW IS 'Alt sou             available           view' , 
	US_LOGWARN IS '# days              F19=LOG             warning' , 
	US_EXPNOTE IS '# days              expire              notes' , 
	US_F3_WARN IS 'F3=Exit             warning' , 
	US_CUR1010 IS 'Cursor              position            _1010' , 
	US_CSTWARN IS 'Cost/div            chg                 warning' , 
	US_ARVDATE IS 'Arv dte             0=Quoted 1=Order' , 
	US_AUTORND IS 'Auto round          0=No 1=Yes' , 
	US_AUTOFRZ IS 'Auto                Freeze              Forecast' , 
	US_DFTLFRZ IS 'Default             Freeze              date' , 
	US_SELVIEW IS 'Selected            products            view' ) ",
  
"LABEL ON COLUMN TST_5DTA.K_USERPRF 
( US_USER TEXT IS 'User ID' , 
	US_COMP TEXT IS 'Company ID default' , 
	US_LOCN TEXT IS 'Location ID default' , 
	US_BUYR TEXT IS 'Buy group default' , 
	US_BIRTH TEXT IS 'User birth date' , 
	US_LASTUPD TEXT IS 'User last update' , 
	US_DATFMT TEXT IS 'Date format default' , 
	US_TIMFMT TEXT IS 'Time format default' , 
	US_TIMADJS TEXT IS 'Time adjustment hours' , 
	US_ALARM TEXT IS 'Alarm preference flag' , 
	US_DEALAL TEXT IS 'Deal allowances $,D,%' , 
	US_DEALPI TEXT IS 'Deal price incre $,D,%' , 
	US_DATESIX TEXT IS 'Date entry 6 digit flg' , 
	US_EWINDOW TEXT IS 'If error display window' , 
	US_ORDVIEW TEXT IS 'Order summary view' , 
	US_ORDMODE TEXT IS 'Order summary mode' , 
	US_PRDVIEW TEXT IS 'Product summary view' , 
	US_PRDOPTN TEXT IS 'Product summary option' , 
	US_HISDSPL TEXT IS 'Product history type' , 
	US_TRACKSG TEXT IS 'Product display T/S >' , 
	US_UNITDSP TEXT IS 'Unit order display 1-6' , 
	US_SELCHEK TEXT IS 'Select check default' , 
	US_PRODSUM TEXT IS 'Prod sum reverse image' , 
	US_MULTWRN TEXT IS 'SOQ multiple warning' , 
	US_ALTVIEW TEXT IS 'Alt sou available view' , 
	US_LOGWARN TEXT IS '# days F19=LOG warning' , 
	US_EXPNOTE TEXT IS '# days expire notes' , 
	US_F3_WARN TEXT IS 'F3=Exit warning' , 
	US_CUR1010 TEXT IS 'Cursor position _1010' , 
	US_CSTWARN TEXT IS 'Cost/div chg warning' , 
	US_ARVDATE TEXT IS 'Arv dte 0=Quoted 1=Order' , 
	US_AUTORND TEXT IS 'Auto round 0=No 1=Yes' , 
	US_AUTOFRZ TEXT IS 'Auto Freeze Forecast' , 
	US_DFTLFRZ TEXT IS 'Default Freeze date' , 
	US_SELVIEW TEXT IS 'Selected products view' ) ",
  
"GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON TST_5DTA.K_USERPRF TO PUBLIC WITH GRANT OPTION ",
  
"GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON TST_5DTA.K_USERPRF TO QSECOFR WITH GRANT OPTION ",

    "INSERT INTO TST_5DTA.K_USERPRF SELECT * FROM WEB_5DTA.K_USERPRF",

];